name: Linting

on:
  push:
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.4

      - name: Setup python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Prepare nox
        run: |
          pip install nox
      - name: Linting
        run: |
          nox -s safety flake8 isort
